baseurl = "http://www.pacollins.com/"
languageCode = "en-us"
title = "Patrick Collins"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 3
disqusShortname = "pacollins"
googleAnalytics = ""

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "Personal Website of Patrick A Collins"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Patrick A Collins"
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    # set this to the section name if section is not post
    viewMorePostLink     = "/blog/"

# Optional Params
    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = true
    faviconVersion       = "2"

    # Load custom CSS or JavaScript files. This replaces the deprecated params
    # minifiedFilesCSS and minifiedFilesJS. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    # Loading min files for exampleSite
    customCSS            = ["/css/main.min.css"]
    customJS             = ["/js/main.min.js"]

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "Patrick  Collins"

    paragraph = "Educator | Conductor | Composer | Arranger | Drill Writter"

    about     = "Patrick is a music educator, techie, and Disney lover located in North Georgia."

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/img/main/logo.png"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = false
    imperfect = true
    width     = ""
    alt       = "Patrick A Collins"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 2

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text

[[menu.main]]
    name = "Home"
    url = "/"
    identifier = "fa fa-home"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    identifier = "fa fa-user"
    weight = 2

[[menu.main]]
    name = "Music"
    url = "/works/music"
    identifier = "fa fa-music"
    weight = 3

[[menu.main]]
    name = "Drill"
    url = "/works/music"
    identifier = "fa fa-male"
    weight = 4

[[menu.main]]
    name = "Programming"
    url = "/works/programming"
    identifier = "fa fa-desktop"
    weight = 5

[[menu.main]]
    name = "Blog"
    url = "/blog"
    identifier = "fa fa-newspaper-o"
    weight = 6

[[menu.main]]
    name = "Categories"
    url = "/categories"
    identifier = "fa fa-sitemap"
    weight = 7

[[menu.main]]
    name = "Contact"
    url = "/contact"
    identifier = "fa fa-envelope-o"
    weight = 8

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = "pacollins"
    bitbucket       = ""
    gitlab          = ""
    jsfiddle        = ""
    codepen         = ""
    freecodecamp    = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = "patrickacollins"
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "pacollins1"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = "aranace"
    pinterest       = ""
    googleplus      = ""
    facebook        = "pacollins"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "pacollins"
    email           = "patrick@pacollins.com"
